version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.13
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/mongoose"
    versions:
    - 5.10.3
    - 5.10.4
  - dependency-name: "@shootismoke/convert"
    versions:
    - 0.6.4
    - 0.8.5
  - dependency-name: "@shootismoke/dataproviders"
    versions:
    - 0.6.4
    - 0.8.5
  - dependency-name: mongodb
    versions:
    - 3.6.4
    - 3.6.5
  - dependency-name: apollo-server-testing
    versions:
    - 2.19.2
  - dependency-name: graphql
    versions:
    - 15.4.0
