language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
services:
  - mongodb
install:
  - yarn install
script:
  - now dev & # run in daemon not to block following scripts
  - sleep 15 # for mongodb
  - yarn test:e2e
